# Generated by Django 4.2.5 on 2023-11-02 14:13

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Airline',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('airlineID', models.CharField(default='000', max_length=3, unique=True)),
                ('name', models.CharField(max_length=50)),
            ],
        ),
        migrations.CreateModel(
            name='Airport',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50)),
                ('x', models.IntegerField(default=0)),
                ('y', models.IntegerField(default=0)),
            ],
        ),
        migrations.CreateModel(
            name='Runway',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('runwayID', models.CharField(default='000', max_length=10, unique=True)),
                ('size', models.CharField(choices=[('S', 'Small'), ('M', 'Medium'), ('L', 'Large')], max_length=1)),
                ('airport', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='atc_app.airport')),
            ],
        ),
        migrations.CreateModel(
            name='Plane',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('planeID', models.CharField(default='0000', max_length=10, unique=True)),
                ('size', models.CharField(choices=[('S', 'Small'), ('M', 'Medium'), ('L', 'Large')], max_length=1)),
                ('capacity', models.IntegerField()),
                ('heading', models.FloatField(null=True)),
                ('speed', models.IntegerField(null=True)),
                ('status', models.CharField(choices=[('AG', 'At Gate'), ('OR', 'On Runway'), ('IF', 'In Flight')], default='AG', max_length=2)),
                ('arrival_time', models.DateTimeField(null=True)),
                ('landing_time', models.DateTimeField(null=True)),
                ('takeOff_time', models.DateTimeField(null=True)),
                ('airline', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='atc_app.airline')),
                ('destination', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='plane_dest', to='atc_app.airport')),
                ('origin', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='plane_origin', to='atc_app.airport')),
                ('runway', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='atc_app.runway')),
            ],
        ),
        migrations.CreateModel(
            name='Gate',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('gateID', models.CharField(default='000', max_length=10, unique=True)),
                ('size', models.CharField(choices=[('S', 'Small'), ('M', 'Medium'), ('L', 'Large')], max_length=1)),
                ('airline', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='atc_app.airline')),
                ('airport', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='atc_app.airport')),
            ],
        ),
    ]
