# Generated by Django 4.1.1 on 2023-11-04 12:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('atc_app', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='gate',
            name='gateID',
            field=models.CharField(default='000', max_length=3, unique=True),
        ),
        migrations.AlterField(
            model_name='plane',
            name='heading',
            field=models.FloatField(default=0, verbose_name=3),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='plane',
            name='planeID',
            field=models.CharField(default='0000', max_length=4, unique=True),
        ),
        migrations.AlterField(
            model_name='plane',
            name='speed',
            field=models.IntegerField(),
        ),
        migrations.AlterField(
            model_name='runway',
            name='runwayID',
            field=models.CharField(default='000', max_length=3, unique=True),
        ),
    ]
