# Generated by Django 4.2.4 on 2023-12-02 18:56

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('atc_app', '0002_alter_gate_gateid_alter_plane_heading_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='plane',
            name='gate',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='atc_app.gate'),
        ),
    ]
