# Generated by Django 4.2.4 on 2023-12-02 22:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('atc_app', '0003_plane_gate'),
    ]

    operations = [
        migrations.AddField(
            model_name='plane',
            name='pass_count',
            field=models.IntegerField(default=0),
        ),
    ]
