# Generated by Django 4.2.5 on 2023-12-05 11:37

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('atc_app', '0005_remove_airline_id_remove_airline_name_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='gate',
            name='airline',
        ),
        migrations.RemoveField(
            model_name='gate',
            name='airport',
        ),
    ]
