# Generated by Django 4.2.5 on 2023-12-05 11:39

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('atc_app', '0006_remove_gate_airline_remove_gate_airport'),
    ]

    operations = [
        migrations.AddField(
            model_name='gate',
            name='airline',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='atc_app.airline'),
        ),
        migrations.AddField(
            model_name='gate',
            name='airport',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='atc_app.airport'),
        ),
    ]
