# Generated by Django 4.2.5 on 2023-12-05 11:40

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('atc_app', '0007_gate_airline_gate_airport'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='plane',
            name='airline',
        ),
        migrations.RemoveField(
            model_name='plane',
            name='destination',
        ),
        migrations.RemoveField(
            model_name='plane',
            name='gate',
        ),
        migrations.RemoveField(
            model_name='plane',
            name='origin',
        ),
        migrations.RemoveField(
            model_name='plane',
            name='runway',
        ),
        migrations.RemoveField(
            model_name='runway',
            name='airport',
        ),
    ]
