# Generated by Django 4.2.5 on 2023-12-05 11:43

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('atc_app', '0009_plane_airline_plane_destination_plane_gate_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='runway',
            name='airport',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='atc_app.airport'),
        ),
    ]
