# Generated by Django 4.2.5 on 2023-12-05 11:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('atc_app', '0010_runway_airport'),
    ]

    operations = [
        migrations.AlterField(
            model_name='plane',
            name='heading',
            field=models.FloatField(null=True, verbose_name=3),
        ),
    ]
