# Generated by Django 4.2.5 on 2023-12-05 11:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('atc_app', '0011_alter_plane_heading'),
    ]

    operations = [
        migrations.AlterField(
            model_name='plane',
            name='speed',
            field=models.IntegerField(default=0),
        ),
    ]
